from django.urls import path
from fashionshop import views

urlpatterns = [
    #path('home', views.home_action, name='home'),
    path('item/<int:id>', views.item_action, name='item'),
    path('all_review/<int:id>', views.get_all_review_ajax),
    path('get-highest-rating/<int:id>', views.get_highest_rating_ajax),
    path('get-lowest-rating/<int:id>', views.get_lowest_rating_ajax),
    path('get-star-rating/<int:id>/<int:rating_num>', views.get_star_rating_ajax),
    path('get-picture/<int:id>', views.get_picture_ajax),
    path('login', views.login_action, name='login'),
    path('register', views.register_action, name='register'),
    path('my_profile', views.profile_action, name='my_profile'),
    path('order', views.order, name='order'),
    path('address', views.address, name='address'),
    path('all_items', views.all_items_action, name='all_items'),
    path('all_items/<gender>', views.all_items_action, name='all_items'),
    path('all_items/<gender>/<genre>', views.all_items_action, name='all_items'),
    # path('women_items', views.women_items_action, name='women_items'),
    # path('women_tops', views.women_tops_action, name='women_tops'),
    path('base', views.base_action, name='base'),
    path('', views.all_items_action, name='home'),
    path('cart', views.cart_action, name='cart'),
    path('update_ship', views.updateShip, name='update_ship'),
    path('clear_cart', views.clearCart, name='clear_cart'),
    # path('update_orderitem_in_page', views.update_orderitem_in_page, name='update_orderitem_in_page'),
    path('update_item', views.updateItem, name='update_item'),
    path('update_item_main', views.updateItemMain, name='update_item_main'),
    path('update_item_signle', views.updateItemSignle, name='update_item_signle'),
    path('checkout', views.checkout_action, name='checkout'),
    path('reset_pw', views.reset_password, name='reset_pw'),
    path('store', views.store_locator, name='store'),
    path('detail', views.detail, name='detail'),
    path('logout', views.logout, name='logout'),
    path('payment/<int:orderId>', views.payment_action, name='payment'),
]
